### ISSUE TITLE
Does not work on ruby 3.0.0 and higher

### ISSUE THREAD

**Issue by pjapkar** [makandra/cucumber_priority#5]
It gives an error cannot load such file -- cucumber/rb_support/rb_language (LoadError).
rb_support foler removed from  ruby 3.0.0 release. it was there in beta

**Comment by kratob** [comment]
This is about cucumber 3, not ruby 3.

I can confirm. We have tests against `3.0.0.pre.1`, but apparently things broke after that.

**Comment by dmilisic** [comment]
this is now fixed with cucumber_priority v0.3.1
